### PR TITLE
Development

### PR DESCRIPTION
**Pull request by 8thDay**
Adds ability for user to create their own links.
Corrects issues with to-do list.
Fixes bugs.

### CODE REVIEW

**Comment by reuben-jones** [comment]
Phew! That's a lot of work. :)

At first I was going to ask why we were ignoring the package.json, but then I remembered this isn't a node app. :)

My only other question is whether the .editorconfig file is necessary? I'm not quite sure what it's for—a specific editor? @8thDay 

Otherwise, everything looks good! Thanks for making my code better.

**Review by reuben-jones — APPROVED** [review]

**Comment by reuben-jones** [comment]
(Just realized that .editorconfig had been deleted, silly question)

**Comment by 8thDay** [comment]
@mrreubenjones Thanks for working through it.

Rather than just modifying .editorconfig, this update deletes the whole file. (lol, I see you noticed this, as I was writing my reply). It was part of an aborted plan to enforce our style guide in the editor. (package.json made it into .gitignore for similar reasons!)

You can check out more about how it works here: http://editorconfig.org/ 
But, basically, it's a way of sharing a single config (and therefore, consistent coding styles) between developers who are using different editors/IDEs. (It can also allow you to easily use different styling conventions for different projects, in the same editor).

**Comment by reuben-jones** [comment]
Ah yes, that makes sense. Thanks for the explanation!

**Pull request merged**
