### PR TITLE
Development

### PR DESCRIPTION
**Pull request by 8thDay**
Version 1.0.0
Replaces 1.0.0 alpha.

### CODE REVIEW

**Comment by DavidLarsKetch** [comment]
*The Great Second Merge*

**Review by DavidLarsKetch — APPROVED** [review]
Wow! We did it. Now to open a load of issues for all the bugs we're sure to find now :wink:!

**Comment by misomighty** [comment]
I cackled at the very apparent bug in the todo list screenshot. It says that there are 4 tasks when you can only see 3. This will be fixed in my upcoming PR. hehe
Great job everyone!

**Review by misomighty — COMMENTED** [review]
Users not being able to add tasks to a new todo list is a pretty major bug. Should we merge it now or after?

**Pull request merged**
