### PR TITLE
Adds to Unsplash API query parameters to filter for landscape photos

### LINKED ISSUE #54: Some backgrounds look bad
Unsplash is giving us backgrounds that are in portrait, which are not optimal for our extension.

### PR DESCRIPTION
**Pull request by DavidLarsKetch**
Fixes #54 by adding a query parameter filtering for landscape photos. This solution doesn't prevent photos from being cropped since 'landscape' could mean an aspect ratio nearly 1:1 and most computer screens have an aspect ratio of 16:10/16:9. But, this does help prevent extreme cropping, as was happening with 'portrait' photos.

### CODE REVIEW

**Comment by 8thDay** [comment]
I notice that the collection number is different in your modified code. Is that a deliberate change?

**Comment by DavidLarsKetch** [comment]
It wasn't - I'm not aware which one is the correct collection number.

**Comment by 8thDay** [comment]
1291922 is the number of Jordan's collection. I think that's the one we've been using most recently. The pictures are very similar to collection 575196, with the addition of some landscapes. And it has the benefit of being under the control of a team member, so no one can swap out the images unexpectedly!

**Comment by DavidLarsKetch** [comment]
Cool, let me check to see what happened in my commits and revert back or make a new commit.

**Pull request closed without merging**
